from util.super_enum import SuperEnum


class BrokerEvent(SuperEnum):

    ON_CANDLE_CLOSE = 'ON_CANDLE_CLOSE'

    ON_IN_POSITION = 'ON_IN_POSITION'
    ON_POSITION_IN_PROFIT = 'ON_POSITION_IN_PROFIT'
    ON_POSITION_IN_LOSS = 'ON_POSITION_IN_LOSS'

    ON_NOT_IN_POSITION = 'ON_NOT_IN_POSITION'

    ON_POSITION_OPEN = 'ON_POSITION_OPEN'
    ON_POSITION_ADJUST = 'ON_POSITION_ADJUST'
    ON_POSITION_CLOSE = 'ON_POSITION_CLOSE'

    ON_ORDERS_CREATE = 'ON_ORDERS_CREATE'
    ON_ORDERS_FILL = 'ON_ORDERS_FILL'
    ON_ORDERS_CANCEL = 'ON_ORDERS_CANCEL'

    ON_BALANCE_CHANGE = 'ON_BALANCE_CHANGE'

    ON_LEVERAGE_CHANGE = 'ON_LEVERAGE_CHANGE'

    def text(self):
        return str(self.value)[3:].capitalize().replace('_', ' ')
